version: "3"
services:
  nginx:
    image: nginx
    container_name: nutapp
    ports:
      - 7200:7200
    volumes:
      - ./utils/nginx:/etc/nginx/conf.d
    depends_on:
      - ui
      - api
  ui:
    container_name: nutapp-ui
    build:
      context: ./ui
      dockerfile: nutapp-ui.dockerfile
    volumes:
      - ./ui:/code
      - /code/node_modules
    ports:
      - 7200
    stdin_open: true
    tty: true
  api:
    build:
      context: ./api
      dockerfile: nutapp.dockerfile
    command: python3.8 manage.py runserver 0.0.0.0:7200
    volumes:
      - ./api:/code
      - /code/.git
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    ports:
      - 7200
    container_name: nutapp-api
  mysql:
    image: mariadb:10.4
    volumes:
      - ./create_databases:/docker-entrypoint-initdb.d
    container_name: nutapp-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
