# Generated by Django 4.1.7 on 2023-03-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accumulated_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='streak_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
