# Generated by Django 4.1.7 on 2023-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_accumulated_score_patient_streak_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='days_off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
