# Generated by Django 4.1.7 on 2023-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedmeal',
            name='items',
            field=models.JSONField(),
        ),
    ]
