# Generated by Django 4.1.7 on 2023-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0003_rename_meal_meal_planned_meal_meal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='items',
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
    ]
