# Generated by Django 4.1.7 on 2023-03-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('meal_plan', '0004_meal_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review')], max_length=20),
            preserve_default=False,
        ),
    ]
