# Generated by Django 4.1.7 on 2023-03-26 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0005_meal_patient_meal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 26, 19, 11, 35, 15395, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
