# Generated by Django 4.1.7 on 2023-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0006_meal_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review')], default='pending_review', max_length=20),
        ),
    ]
