# Generated by Django 4.1.7 on 2023-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan', '0007_alter_meal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
